import { Language } from './types';

export const ALL_NOTES_SHARP = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

export const SCALES = {
    major: { name: 'Major', intervals: [2, 2, 1, 2, 2, 2, 1] },
    naturalMinor: { name: 'Natural Minor', intervals: [2, 1, 2, 2, 1, 2, 2] },
    harmonicMinor: { name: 'Harmonic Minor', intervals: [2, 1, 2, 2, 1, 3, 1] },
    melodicMinor: { name: 'Melodic Minor', intervals: [2, 1, 2, 2, 2, 2, 1] },
    majorBlues: { name: 'Major Blues', intervals: [2, 1, 1, 3, 2, 3] },
    minorBlues: { name: 'Minor Blues', intervals: [3, 2, 1, 1, 3, 2] },
    pentatonicMajor: { name: 'Pentatonic Major', intervals: [2, 2, 3, 2, 3] },
    pentatonicMinor: { name: 'Pentatonic Minor', intervals: [3, 2, 2, 3, 2] },
    wholeTone: { name: 'Whole Tone', intervals: [2, 2, 2, 2, 2, 2] },
};

export const CHORDS = {
    major: { name: 'Major', intervals: [0, 4, 7] },
    minor: { name: 'Minor', intervals: [0, 3, 7] },
    diminished: { name: 'Diminished', intervals: [0, 3, 6] },
    augmented: { name: 'Augmented', intervals: [0, 4, 8] },
    major7: { name: 'Major 7th', intervals: [0, 4, 7, 11] },
    minor7: { name: 'Minor 7th', intervals: [0, 3, 7, 10] },
    dominant7: { name: 'Dominant 7th', intervals: [0, 4, 7, 10] },
};

export const UI_TEXT = {
    [Language.EN]: {
        title: "Sam Deeven Music Theory",
        home: "Home",
        scales: "Scales",
        chords: "Chords",
        familyChords: "Family Chords",
        circleOfFifths: "Circle Of Fifths",
        progressions: "Chord Progressions",
        exercises: "Exercises",
        chat: "AI Chat",
        about: "About",
        contact: "Contact",
        searchPlaceholder: "Search for a topic...",
        transpose: "Transpose",
        selectRootNote: "Select Root Note",
        selectScale: "Select Scale",
        selectChord: "Select Chord",
        getExplanation: "Get Explanation",
        explanation: "Explanation",
        notesInScale: "Notes in Scale:",
        notesInChord: "Notes in Chord:",
        diatonicChords: "Diatonic Chords",
        timeSignature: "Time Signature",
        regenerate: "Regenerate",
        welcome: "Welcome to Sam Deeven Music Theory",
        welcomeDesc: "Your interactive guide to understanding music. Select a topic from the menu to begin.",
        generating: "Generating with AI...",
        chatWelcome: "Ask me anything about music theory!",
        chatPlaceholder: "Type your question here...",
        inversions: "Chord Inversions",
        rootPosition: "Root Position",
        firstInversion: "1st Inversion",
        secondInversion: "2nd Inversion",
        thirdInversion: "3rd Inversion",
    },
    [Language.TE]: {
        title: "శ్యామ్ దీవెన్ సంగీత సిద్ధాంతం",
        home: "హోమ్",
        scales: "స్కేల్స్ (Scales)",
        chords: "కార్డ్స్ (Chords)",
        familyChords: "ఫ్యామిలీ కార్డ్స్",
        circleOfFifths: "సర్కిల్ ఆఫ్ ఫిఫ్త్స్",
        progressions: "కార్డ్ ప్రోగ్రెషన్స్",
        exercises: "వ్యాయామాలు (Exercises)",
        chat: "AI చాట్",
        about: "గురించి",
        contact: "సంప్రదించండి",
        searchPlaceholder: "ఒక అంశం కోసం శోధించండి...",
        transpose: "ట్రాన్స్‌పోజ్ (Transpose)",
        selectRootNote: "రూట్ నోట్ ఎంచుకోండి",
        selectScale: "స్కేల్ ఎంచుకోండి",
        selectChord: "కార్డ్ ఎంచుకోండి",
        getExplanation: "వివరణ పొందండి",
        explanation: "వివరణ",
        notesInScale: "స్కేల్‌లోని నోట్స్:",
        notesInChord: "కార్డ్‌లోని నోట్స్:",
        diatonicChords: "డయాటోనిక్ కార్డ్స్",
        timeSignature: "టైమ్ సిగ్నేచర్",
        regenerate: "పునఃసృష్టించు",
        welcome: "శ్యామ్ దీవెన్ సంగీత సిద్ధాంతానికి స్వాగతం",
        welcomeDesc: "సంగీతాన్ని అర్థం చేసుకోవడానికి మీ ఇంటరాక్టివ్ గైడ్. ప్రారంభించడానికి మెను నుండి ఒక అంశాన్ని ఎంచుకోండి.",
        generating: "AI తో జెనరేట్ చేయబడుతోంది...",
        chatWelcome: "సంగీత సిద్ధాంతం గురించి నన్ను ఏదైనా అడగండి!",
        chatPlaceholder: "మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...",
        inversions: "కార్డ్ ఇన్వర్షన్స్",
        rootPosition: "రూట్ పొజిషన్",
        firstInversion: "1వ ఇన్వర్షన్",
        secondInversion: "2వ ఇన్వర్షన్",
        thirdInversion: "3వ ఇన్వర్షన్",
    }
};

export const TIME_SIGNATURES = ['4/4', '3/4', '2/4', '6/8', '5/8', '7/8'];